version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
    restart: always
    volumes: 
      - ./docker-volumes/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
  web: 
    build: .
    depends_on: 
      - db
    ports: 
      - "4000:4000"