version: "3.7"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
    ports:
      - 4000:4000
    networks:
      - webnet
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start:prod"]

  db:
    container_name: db
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRE_DATABASE: postgres
    restart: always
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - webnet
networks:
  webnet:
