version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
      POSTGRES: nest
    restart: always
    ports:
      - "5432:5432"
  web: 
    image: firstwwebsitebackend
    depends_on: 
      - db
    ports: 
      - "4000:4000"